### ISSUE TITLE
Support SwiftUI?

### ISSUE THREAD

**Issue by ngocdaothanh** [flowkey/UIKit-cross-platform#297]
Hi, what do you think about supporting SwiftUI syntax?

**Comment by ephemer** [comment]
Hi @ngocdaothanh SwiftUI would be quite interesting for us as well but we currently don't have plans to work on it. Ideally we'd wait until their APIs become a little more stable because there are some ongoing issues with certain parts of SwiftUI that we'd love to see fixed first.

Also we'd then need to find time and business need to make the switch, but it's certainly interesting for us medium-term. We will update the docs if we start any experiments in that direction! I think that answers the question so I'm going to close this issue now.
